// Portable digital SoC source list. Top: soc.
// First-party contributions: Apache-2.0; third-party terms remain in force.
// Generic primitives are unconditional; no simulator/platform macro is required.
+define+SYNTHESIS
+incdir+${SRC_DIR}/misc/include/
+incdir+${SRC_DIR}/soc_axi/include/
+incdir+${SRC_DIR}/include/
+incdir+${SRC_DIR}/dma/include/
${SRC_DIR}/cpu_cva6/include/config_pkg.sv
${SRC_DIR}/cpu_cva6/include/cv64a6_config_pkg.sv
${SRC_DIR}/cpu_cva6/include/riscv_pkg.sv
${SRC_DIR}/cpu_cva6/include/ariane_pkg.sv
${SRC_DIR}/cpu_cva6/include/wt_cache_pkg.sv
${SRC_DIR}/cpu_cva6/include/cvxif_pkg.sv
${SRC_DIR}/soc_pkg.sv
${SRC_DIR}/soc_axi/axi_bus/include/axi_pkg.sv
${SRC_DIR}/soc_axi/axi_bus/include/ariane_axi_pkg.sv
${SRC_DIR}/soc_axi/axi_bus/include/ariane_axi_soc_pkg.sv
${SRC_DIR}/soc_axi/axi_bus/include/axi_intf.sv
${SRC_DIR}/soc_axi/reg_bus/reg_intf.sv
${SRC_DIR}/soc_axi/riscv-dbg/dm_pkg.sv
${SRC_DIR}/misc/cf_math_pkg.sv
${SRC_DIR}/dma/idma_pkg.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_unit_pkg.sv
${SRC_DIR}/soc.sv
${SRC_DIR}/soc_axi/peripheral.sv
${SRC_DIR}/soc_axi/axi_bus/axi_id_prepend.sv
${SRC_DIR}/soc_axi/axi_bus/axi_atop_filter.sv
${SRC_DIR}/soc_axi/axi_bus/axi_err_slv.sv
${SRC_DIR}/soc_axi/axi_bus/axi_mux.sv
${SRC_DIR}/soc_axi/axi_bus/axi_demux.sv
${SRC_DIR}/soc_axi/axi_bus/axi_xbar.sv
${SRC_DIR}/soc_axi/axi_bus/axi_lite_interface.sv
${SRC_DIR}/soc_axi/axi_bus/axi_slice/axi_ar_buffer.sv
${SRC_DIR}/soc_axi/axi_bus/axi_slice/axi_aw_buffer.sv
${SRC_DIR}/soc_axi/axi_bus/axi_slice/axi_b_buffer.sv
${SRC_DIR}/soc_axi/axi_bus/axi_slice/axi_r_buffer.sv
${SRC_DIR}/soc_axi/axi_bus/axi_slice/axi_w_buffer.sv
${SRC_DIR}/soc_axi/axi_bus/axi_slice/axi_single_slice.sv
${SRC_DIR}/soc_axi/bus_converter/axi2mem.sv
${SRC_DIR}/soc_axi/bus_converter/axi2mem_multi_cycle_read.sv
${SRC_DIR}/soc_axi/bus_converter/apb_to_reg.sv
${SRC_DIR}/soc_axi/bus_converter/axi2apb_64_32.sv
${SRC_DIR}/soc_axi/riscv-dbg/dm_csrs.sv
${SRC_DIR}/soc_axi/riscv-dbg/dmi_cdc.sv
${SRC_DIR}/soc_axi/riscv-dbg/dmi_jtag.sv
${SRC_DIR}/soc_axi/riscv-dbg/dmi_jtag_tap.sv
${SRC_DIR}/soc_axi/riscv-dbg/dm_mem.sv
${SRC_DIR}/soc_axi/riscv-dbg/dm_sba.sv
${SRC_DIR}/soc_axi/riscv-dbg/dm_top.sv
${SRC_DIR}/soc_axi/riscv-dbg/debug_rom.sv
${SRC_DIR}/soc_axi/clint.sv
${SRC_DIR}/soc_axi/bootrom.sv
${SRC_DIR}/soc_axi/main_mem/main_mem_wrapper.sv
${SRC_DIR}/soc_axi/rv_plic/plic_regmap.sv
${SRC_DIR}/soc_axi/rv_plic/rv_plic_gateway.sv
${SRC_DIR}/soc_axi/rv_plic/rv_plic_target.sv
${SRC_DIR}/soc_axi/rv_plic/plic_top.sv
${SRC_DIR}/soc_axi/apb_timer/apb_timer.sv
${SRC_DIR}/soc_axi/apb_timer/timer.sv
${SRC_DIR}/soc_axi/apb_uart/apb_uart.sv
${SRC_DIR}/soc_axi/apb_uart/slib_clock_div.sv
${SRC_DIR}/soc_axi/apb_uart/slib_counter.sv
${SRC_DIR}/soc_axi/apb_uart/slib_edge_detect.sv
${SRC_DIR}/soc_axi/apb_uart/slib_fifo.sv
${SRC_DIR}/soc_axi/apb_uart/slib_input_filter.sv
${SRC_DIR}/soc_axi/apb_uart/slib_input_sync.sv
${SRC_DIR}/soc_axi/apb_uart/slib_mv_filter.sv
${SRC_DIR}/soc_axi/apb_uart/uart_baudgen.sv
${SRC_DIR}/soc_axi/apb_uart/uart_interrupt.sv
${SRC_DIR}/soc_axi/apb_uart/uart_receiver.sv
${SRC_DIR}/soc_axi/apb_uart/uart_transmitter.sv
${SRC_DIR}/soc_axi/clk/dco_regs.sv
${SRC_DIR}/misc/rstgen.sv
${SRC_DIR}/misc/rstgen_bypass.sv
${SRC_DIR}/misc/addr_decode.sv
${SRC_DIR}/misc/stream_register.sv
${SRC_DIR}/misc/stream_fifo.sv
${SRC_DIR}/misc/stream_fifo_optimal_wrap.sv
${SRC_DIR}/misc/cdc_2phase.sv
${SRC_DIR}/misc/spill_register_flushable.sv
${SRC_DIR}/misc/spill_register.sv
${SRC_DIR}/misc/fifo_v1.sv
${SRC_DIR}/misc/fifo_v2.sv
${SRC_DIR}/misc/fall_through_register.sv
${SRC_DIR}/misc/cluster_clk_cells.sv
${SRC_DIR}/misc/pulp_clk_cells.sv
${SRC_DIR}/misc/passthrough_stream_fifo.sv
${SRC_DIR}/misc/tc_clk.v
${SRC_DIR}/cpu_cva6/cva6.sv
${SRC_DIR}/misc/fifo_v3.sv
${SRC_DIR}/misc/lfsr.sv
${SRC_DIR}/misc/lzc.sv
${SRC_DIR}/misc/rr_arb_tree.sv
${SRC_DIR}/misc/shift_reg.sv
${SRC_DIR}/misc/popcount.sv
${SRC_DIR}/misc/exp_backoff.sv
${SRC_DIR}/misc/counter.sv
${SRC_DIR}/misc/delta_counter.sv
${SRC_DIR}/cpu_cva6/alu.sv
${SRC_DIR}/cpu_cva6/branch_unit.sv
${SRC_DIR}/cpu_cva6/compressed_decoder.sv
${SRC_DIR}/cpu_cva6/controller.sv
${SRC_DIR}/cpu_cva6/csr_buffer.sv
${SRC_DIR}/cpu_cva6/csr_regfile.sv
${SRC_DIR}/cpu_cva6/decoder.sv
${SRC_DIR}/cpu_cva6/ex_stage.sv
${SRC_DIR}/cpu_cva6/instr_realign.sv
${SRC_DIR}/cpu_cva6/id_stage.sv
${SRC_DIR}/cpu_cva6/issue_read_operands.sv
${SRC_DIR}/cpu_cva6/issue_stage.sv
${SRC_DIR}/cpu_cva6/load_unit.sv
${SRC_DIR}/cpu_cva6/load_store_unit.sv
${SRC_DIR}/cpu_cva6/lsu_bypass.sv
${SRC_DIR}/cpu_cva6/mult.sv
${SRC_DIR}/cpu_cva6/multiplier.sv
${SRC_DIR}/cpu_cva6/serdiv.sv
${SRC_DIR}/cpu_cva6/perf_counters.sv
${SRC_DIR}/cpu_cva6/ariane_regfile_ff.sv
${SRC_DIR}/cpu_cva6/scoreboard.sv
${SRC_DIR}/cpu_cva6/store_buffer.sv
${SRC_DIR}/cpu_cva6/amo_buffer.sv
${SRC_DIR}/cpu_cva6/store_unit.sv
${SRC_DIR}/cpu_cva6/commit_stage.sv
${SRC_DIR}/cpu_cva6/axi_shim.sv
${SRC_DIR}/cpu_cva6/frontend/btb.sv
${SRC_DIR}/cpu_cva6/frontend/bht.sv
${SRC_DIR}/cpu_cva6/frontend/ras.sv
${SRC_DIR}/cpu_cva6/frontend/instr_scan.sv
${SRC_DIR}/cpu_cva6/frontend/instr_queue.sv
${SRC_DIR}/cpu_cva6/frontend/frontend.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/wt_dcache_ctrl.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/wt_dcache_mem.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/wt_dcache_missunit.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/wt_dcache_wbuffer.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/wt_dcache.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/cva6_icache.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/wt_cache_subsystem.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/wt_axi_adapter.sv
${SRC_DIR}/cpu_cva6/cache_subsystem/axi_adapter.sv
${SRC_DIR}/dllm_acc/cache_PE_acc_cfg.sv
${SRC_DIR}/dllm_acc/dllm_acc_wrapper.sv
${SRC_DIR}/dllm_acc/sfu_cfg.sv
${SRC_DIR}/dllm_acc/sfu_ctrl.sv
${SRC_DIR}/dllm_acc/cache_PE_accelerator/act_gen_column.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/act_gen_unit.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/adder_tree_8b_unit.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/C2C_intf.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/cache_PE_accelerator.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/cache_PE_array.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/cache_PE_column.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/cache_PE_core.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/cache_PE_core_ctrlr.v
${SRC_DIR}/dllm_acc/cache_PE_accelerator/cache_PE_unit.v
${SRC_DIR}/dllm_acc/special_function_unit/bf16_adder.sv
${SRC_DIR}/dllm_acc/special_function_unit/bf16_dequant.sv
${SRC_DIR}/dllm_acc/special_function_unit/sfu_acc_lane.sv
${SRC_DIR}/dllm_acc/special_function_unit/sfu_dequant_lane.sv
${SRC_DIR}/dllm_acc/special_function_unit/sfu_tile_classifier.sv
${SRC_DIR}/dllm_acc/special_function_unit/sfu_acc_tree.sv
${SRC_DIR}/dllm_acc/special_function_unit/special_function_unit.sv
${SRC_DIR}/dma/idma_axi_read.sv
${SRC_DIR}/dma/idma_axi_write.sv
${SRC_DIR}/dma/idma_backend.sv
${SRC_DIR}/dma/idma_channel_coupler.sv
${SRC_DIR}/dma/idma_dataflow_element.sv
${SRC_DIR}/dma/idma_legalizer.sv
${SRC_DIR}/dma/idma_legalizer_page_splitter.sv
${SRC_DIR}/dma/idma_transport.sv
${SRC_DIR}/misc/my_counter.sv
${SRC_DIR}/dllm_acc/vector_unit/configurable_mul_pe.sv
${SRC_DIR}/dllm_acc/vector_unit/int4x4_mul.sv
${SRC_DIR}/dllm_acc/vector_unit/max_tile_update_unit.sv
${SRC_DIR}/dllm_acc/vector_unit/pe_array_ctrl.sv
${SRC_DIR}/dllm_acc/vector_unit/token_acc_unit.sv
${SRC_DIR}/dllm_acc/vector_unit/token_promote_tile_score_unit.sv
${SRC_DIR}/dllm_acc/vector_unit/token_promotion_unit.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_align_lane.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_bf16_add_lane.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_bf16_mul_lane.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_quant_lane.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_unit.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_unit_axi_cfg.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_unit_ctrl.sv
${SRC_DIR}/dllm_acc/vector_unit/vector_unit_rf_frontend.sv
${SRC_DIR}/dllm_acc/vector_unit/topk/topk_counter.sv
${SRC_DIR}/dllm_acc/vector_unit/topk/topk_ctrlr.sv
${SRC_DIR}/dllm_acc/vector_unit/topk/topk_HIT.sv
${SRC_DIR}/dllm_acc/vector_unit/topk/topk_MIN.sv
${SRC_DIR}/dllm_acc/vector_unit/topk/topk_SEL.sv
${SRC_DIR}/dllm_acc/vector_unit/topk/topk_ss.sv
${SRC_DIR}/dllm_acc/vector_unit/topk/topk_wrapper.sv
${SRC_DIR}/misc/gclk_unit.v
${SRC_DIR}/misc/mux2_unit.v
${SRC_DIR}/misc/mux4_unit.v
${SRC_DIR}/misc/sram_wrappers.v
${SRC_DIR}/misc/tc_sram.sv
${SRC_DIR}/misc/tc_sram_wrapper.sv
${SRC_DIR}/misc/sram.sv
